package com.tesis.backendCuadernoDigital.enums;

public enum LogAccion {
    USUARIO_LOGIN,
    USUARIO_ERROR_LOGIN,
    USUARIO_ERROR_LOGIN_USUARIO_INACTIVO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION,
    USUARIO_ELIMINACION,
    USUARIO_CAMBIO_CONTRASENIA,
    USUARIO_RECUPERACION_CONTRASENIA,
    USUARIO_ALTA,
    USUARIO_BAJA,

    RIEGO_CREACIÓN,
    RIEGO_MODIFICACIÓN,
    RIEGO_ALTA,
    RIEGO_BAJA,

    PLAGA_CREACIÓN,
    PLAGA_MODIFICACIÓN,
    PLAGA_ALTA,
    PLAGA_BAJA,

    AGROQUÍMICO_CREACIÓN,
    AGROQUÍMICO_MODIFICACIÓN,
    AGROQUÍMICO_ALTA,
    AGROQUÍMICO_BAJA,
    AGROQUÍMICO_APLICACIÓN,

    CREACIÓN_CULTIVO,
    MODIFICACIÓN_CULTIVO,
    ALTA_CULTIVO,
    BAJA_CULTIVO,

    REPORTE_ESTADISTICO_CREACIÓN,
    REPORTE_ESTADISTICO_MODIFICACIÓN,
    REPORTE_ESTADISTICO_ALTA,
    REPORTE_ESTADISTICO_BAJA,

    INSPECCIONES_CREACIÓN,
    INSPECCIONES_MODIFICACIÓN,
    INSPECCIONES_ALTA,
    INSPECCIONES_BAJA,

    CREACIÓN_PLANTACIÓN,
    BAJA_PLANTACIÓN,
    ALTA_PLANTACIÓN,
    MODIFICACIÓN_PLANTACIÓN,

    CREACIÓN_CULTIVO_ANTERIOR,
    MODIFICACIÓN_CULTIVO_ANTERIOR,
    ALTA_CUADRO,
    BAJA_CUADRO,
    MODIFICACIÓN_CUADRO,

    CREACIÓN_FINCA,
    ALTA_FINCA,
    BAJA_FINCA,
    MODIFICACIÓN_FINCA,

    CREACIÓN_LABOR_SUELO,
    ALTA_LABOR_SUELO,
    BAJA_LABOR_SUELO,
    MODIFICACIÓN_LABOR_SUELO,

    CAMBIO_CONTRASENIA,
    ACTUALIZAR_PERFIL,

    CREACIÓN_RIEGO,
    MODIFICACIÓN_RIEGO,

    CREACIÓN_AGROQUÍMICO,
    MODIFICACIÓN_AGROQUÍMICO,

    APLICACIÓN_AGROQUÍMICO,
    MODIFICACIÓN_APLICACIÓN_AGROQUÍMICO,


    CREACIÓN_ASESORAMIENTO_RIEGO,
    MODIFICAR_ASESORÍA_RIEGO,
    SE_APLICÓ_ASESORÍA_RIEGO,
    CANCELO_APLICACIÓN_ASESORIA_RIEGO,

    CREACIÓN_ASESORAMIENTO_AGROQUÍMICO,
    MODIFICACIÓN_ASESORAMIENTO_AGROQUÍMICO,
    SE_APLIÓ_ASESORÍA_AGROQUÍMICO,
    CANCELO_APLICACIÓN_ASESORÍA_AGROÍMICO





}
