package com.tesis.backendCuadernoDigital.enums;

public enum LogAccion {
    USUARIO_LOGIN,
    USUARIO_ERROR_LOGIN,
    USUARIO_ERROR_LOGIN_USUARIO_INACTIVO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION,
    USUARIO_ELIMINACION,
    USUARIO_CAMBIO_CONTRASENIA,
    USUARIO_RECUPERACION_CONTRASENIA,
    USUARIO_ALTA,
    USUARIO_BAJA,

    RIEGO_CREACION,
    RIEGO_MODIFICACION,
    RIEGO_ALTA,
    RIEGO_BAJA,

    PLAGA_CREACION,
    PLAGA_MODIFICACION,
    PLAGA_ALTA,
    PLAGA_BAJA,

    AGROQUIMICO_CREACION,
    AGROQUIMICO_MODIFICACION,
    AGROQUIMICO_ALTA,
    AGROQUIMICO_BAJA,
    AGROQUIMICO_APLICACION,

    CREACION_CULTIVO,
    MODIFICACION_CULTIVO,
    ALTA_CULTIVO,
    BAJA_CULTIVO,

    REPORTEESTADISTICO_CREACION,
    REPORTEESTADISTICO_MODIFICACION,
    REPORTEESTADISTICO_ALTA,
    REPORTEESTADISTICO_BAJA,

    INSPECCIONES_CREACION,
    INSPECCIONES_MODIFICACION,
    INSPECCIONES_ALTA,
    INSPECCIONES_BAJA,

    CREACION_PLANTACION,
    BAJA_PLANTACION,
    ALTA_PLANTACION,
    MODIFICACION_PLANTACION,




}
